services:
  api:
    build: .
    container_name: roomate-api
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/daroomate
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - POSTGRESQL_HOST=postgresdb
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=daroomate
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - JWT_KEY=your-super-secret-key-that-is-at-least-32-chars-long
      - SPRING_JWT_SECRET=your-super-secret-key-that-is-at-least-32-chars-long
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_ID=your-email@gmail.com
      - EMAIL_PASSWORD=your-app-password
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=your-email@gmail.com
      - SPRING_MAIL_PASSWORD=your-app-password
      - CONTAINER_PORT=8085
    depends_on:
      - postgresdb
    networks:
      - roomate-network

  postgresdb:
    container_name: roomate-db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: daroomate
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roomate-network

volumes:
  postgres_data:

networks:
  roomate-network:
